In [27]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-7.1559e-11,  4.5853e-41, -7.1559e-11],
        [ 4.5853e-41,         nan,  0.0000e+00],
        [ 7.6194e+31,  1.5564e+28,  4.7984e+30],
        [ 6.2121e+22,  1.8370e+25,  1.4603e-19],
        [ 2.7517e+12,  7.5338e+28,  3.0313e+32]])


In [6]:
x = torch.rand(5,3)
print(x)
print(x.size())

tensor([[0.5137, 0.7834, 0.4679],
        [0.7113, 0.4955, 0.0884],
        [0.9886, 0.1686, 0.0328],
        [0.3828, 0.8704, 0.4453],
        [0.1954, 0.7417, 0.9197]])
torch.Size([5, 3])


In [7]:
torch.zeros(5,3,dtype = torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
torch.tensor([[5,5,3],[3,2,2]]) # similar to numpy

tensor([[5, 5, 3],
        [3, 2, 2]])

In [15]:
x.new_ones(5,3,dtype= torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
x = torch.randn_like(x,dtype=torch.float)#overiding is availabe
print(x)

tensor([[-0.7613, -2.6645,  0.0873],
        [ 0.1977, -1.5460, -0.4825],
        [ 0.7168,  0.8678, -2.9543],
        [ 0.9071, -0.7772, -0.9311],
        [ 0.5592,  0.1676, -0.0956]])


In [19]:
y = torch.randn(5,3)

In [21]:
# 3-ways to add
print(x+y)
print(torch.add(x,y))
result = torch.empty(5,3)
torch.add(x,y,out= result)
print(result)

tensor([[-1.3448, -3.1883,  1.0894],
        [-1.3588, -0.3808, -2.0804],
        [ 0.6864,  0.0193, -2.6025],
        [ 2.2672, -2.0404, -2.4126],
        [ 0.1152,  0.0315,  2.6817]])
tensor([[-1.3448, -3.1883,  1.0894],
        [-1.3588, -0.3808, -2.0804],
        [ 0.6864,  0.0193, -2.6025],
        [ 2.2672, -2.0404, -2.4126],
        [ 0.1152,  0.0315,  2.6817]])
tensor([[-1.3448, -3.1883,  1.0894],
        [-1.3588, -0.3808, -2.0804],
        [ 0.6864,  0.0193, -2.6025],
        [ 2.2672, -2.0404, -2.4126],
        [ 0.1152,  0.0315,  2.6817]])


In [23]:
# reshaping similar to numpy reshape
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # same is view(2,8) -1 is inferred from source x
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
# Numpy bridge

# torch(tensor) --> numpy ndarray

a = torch.tensor([5,3,5])
print(a)
a = a.numpy()
print(a)

tensor([5, 3, 5])
[5 3 5]


In [34]:
# torch(tensor) <-- numpy ndarray
a = np.ones(5).astype(np.bool)
print(a)
a = torch.from_numpy(a)
print(a)

[ True  True  True  True  True]
tensor([True, True, True, True, True], dtype=torch.bool)


In [35]:
torch.cuda.is_available()

True

In [45]:
x = np.random.randn(5,3).astype(np.float32)
x = torch.from_numpy(x)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    print(x) # cpu
    print(y) # cuda
    x = x.to(device) # cpu -> cuda
    print(x) # cuda
    print(y) # cuda
    z = x+y
    print(z) # cuda
    print(z.to("cpu", torch.double)) # cpu

tensor([[ 0.1826,  0.0457,  0.5066],
        [-0.1142,  1.7604,  0.5025],
        [-0.3520, -1.0890, -1.0082],
        [-0.0224,  1.4722, -0.0748],
        [ 1.2374, -0.0290,  0.2490]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[ 0.1826,  0.0457,  0.5066],
        [-0.1142,  1.7604,  0.5025],
        [-0.3520, -1.0890, -1.0082],
        [-0.0224,  1.4722, -0.0748],
        [ 1.2374, -0.0290,  0.2490]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[ 1.1826,  1.0457,  1.5066],
        [ 0.8858,  2.7604,  1.5025],
        [ 0.6480, -0.0890, -0.0082],
        [ 0.9776,  2.4722,  0.9252],
        [ 2.2374,  0.9710,  1.2490]], device='cuda:0')
tensor([[ 1.1826,  1.0457,  1.5066],
        [ 0.8858,  2.7604,  1.5025],
        [ 0.6480, -0.0890, -0.0082],
        [ 0.9776,  2.4722,  0.9252],
    